### ISSUE TITLE
CLA document issue

### ISSUE THREAD

**Issue by marado** [jonm/SillyMUD#107]
CONTRIBUTING asks for CLA signing, but points towards https://www.clahub.com/agreements/jonm/SillyMUD which, currently, is not the document it was supposed to be (the entire clahub.com seems to be a spam/ad host, nowadays).

**Comment by jonm** [comment]
Hi, thanks for raising this. I believe CLAs have somewhat fallen out of favor for community projects since this was put up. The [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license) make an “inbound = outbound” default in the absence of a superseding CLA: roughly, that contributors agree to license their contributions under the license of the project (which works for me, at least).

Thoughts on just removing the CLA requirement from `CONTRIBUTING`?

cc @dangitall

**Comment by marado** [comment]
Removing the CLA requirement seems fine to me.

**Comment by jonm** [comment]
I am also fine with my contributions being licensed under the project license, which was the main intent of the (now-defunct) CLA anyway. @dangitall does that work for you?

**Comment by dangitall** [comment]
> I am also fine with my contributions being licensed under the project license,

Fine with me as well!
